#pragma once

#define ORANGE_MOUSE_BUTTON_1         0
#define ORANGE_MOUSE_BUTTON_2         1
#define ORANGE_MOUSE_BUTTON_3         2
#define ORANGE_MOUSE_BUTTON_4         3
#define ORANGE_MOUSE_BUTTON_5         4
#define ORANGE_MOUSE_BUTTON_6         5
#define ORANGE_MOUSE_BUTTON_7         6
#define ORANGE_MOUSE_BUTTON_8         7
#define ORANGE_MOUSE_BUTTON_LAST      ORANGE_MOUSE_BUTTON_8
#define ORANGE_MOUSE_BUTTON_LEFT      ORANGE_MOUSE_BUTTON_1
#define ORANGE_MOUSE_BUTTON_RIGHT     ORANGE_MOUSE_BUTTON_2
#define ORANGE_MOUSE_BUTTON_MIDDLE    ORANGE_MOUSE_BUTTON_3
